name: Build and Analyze With DotNet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x # Matches VS 2022 requirements

    - name: Restore dependencies
      run: dotnet restore MSBuild.sln

    - name: Build
      run: dotnet build MSBuild.sln --no-restore --configuration Release

    - name: Embold Analyse
      run: |
        curl ${{ vars.EMBOLD_SCANNER_URL}} -o browserstack-codequality-scanner-archive.tar.gz
        tar xvf browserstack-codequality-scanner-archive.tar.gz
        echo "Download and extract BrowserStack CQ Scanner done"
        curl --silent --location --request GET "${{ vars.EMBOLD_URL_CS}}/api/v1/repositories/a8238eb805e404219cc4763d72ea3471/scans/config/download" --header "Authorization:Bearer ${{ secrets.EMBOLD_TOKEN_CS}}" -o repository-configuration.json
        echo "Download repository configuration file done"
        ./browserstack-codequality-scanner/bin/embold-scanner analyse -u ${{ vars.EMBOLD_URL_CS}} -t ${{ secrets.EMBOLD_TOKEN_CS}} -r a8238eb805e404219cc4763d72ea3471 -b . -d ./embold-data -c ./repository-configuration.json -v
