name: Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Disables the vulnerability check so the build can finish
      DOTNET_NUGET_AUDIT: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Using ./build.sh solves the "missing properties" error.
    # The DOTNET_NUGET_AUDIT env var (set above) solves the "vulnerability" error.
    - name: Build Repository
      run: |
        chmod +x build.sh
        ./build.sh --configuration Release --ci -p:NuGetAudit=false

    - name: Embold Analyse
      run: |
        curl ${{ vars.EMBOLD_SCANNER_URL}} -o browserstack-codequality-scanner-archive.tar.gz
        tar xvf browserstack-codequality-scanner-archive.tar.gz
        echo "Download and extract BrowserStack CQ Scanner done"
        curl --silent --location --request GET "${{ vars.EMBOLD_URL_CS}}/api/v1/repositories/a8238eb805e404219cc4763d72ea3471/scans/config/download" --header "Authorization:Bearer ${{ secrets.EMBOLD_TOKEN_CS}}" -o repository-configuration.json
        echo "Download repository configuration file done"
        ./browserstack-codequality-scanner/bin/embold-scanner analyse -u ${{ vars.EMBOLD_URL_CS}} -t ${{ secrets.EMBOLD_TOKEN_CS}} -r a8238eb805e404219cc4763d72ea3471 -b . -d ./embold-data -c ./repository-configuration.json -v
    - name: Corona path
      run: | 
        cat .embold/embold_scanner_home/corona/csharpCore/linux/x64/Config/log4net.config
      
